### ISSUE TITLE
2425-W-005 Crawl OSAC's JSON-LD

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-osac#1]
OSAC has a listing of events ready to be scraped: https://www.osac.ca/performing-arts/performances?run=patours

Skip coded the structured data: it includes all required and recommended properties, including the Place sameAs for automated minting of IDs.

Of note:
Skip was unable to push the proper timezone. His site defaults to +00:00. Therefore Skip edited the start times to take into account the wrong time zone offset.

specific instructions from @saumier 
=======
1. Please assign URIs to event blank nodes (domain + UUID) 
2. Please include prov:wasDerivedFrom "url scraped" to all entities on the webpage scrapped
3. I think timezones are fine, so no need to touch them but please double check
4. Use the artdata-orion repo because this is where all the pure JSON-LD crawls go.
5. Provide some comments on the quality of their JSON-LD including violations marked in Artsdata

Pages to crawl
==============
### For Performing arts:

1. Visit page https://www.osac.ca/performing-arts/performances?run=patours to get the list of tours
2. For each tour visit the tour page. Example: https://www.osac.ca/index.php?option=com_content&view=article&id=156&Itemid=1821&artist=Becoming%2Bthe%2BBeatles
https://www.osac.ca/index.php?option=com_content&view=article&id=156&Itemid=1821&artist=Becoming%2Bthe%2BBeatles
3. For each date visit the link to capture the event JSON-LD. Example:
https://www.osac.ca/performing-arts/event/121-PA8812/becoming-the-beatles-dekker-centre

### For Exhibitions:

1. Visit page https://www.osac.ca/visual-media-arts/exhibitionsvma?run=exhibitions to get the list of exhibitions
2. For each exhibition visit the exhibition page. Example: https://www.osac.ca/index.php?option=com_content&view=article&id=157&artist=A+Selection+of+Specimens&Itemid=1822
3. For each date visit the link to capture the event JSON-LD. Example:
https://osac.ca/visual-media-arts/event/112-VA4088/a-selection-of-specimens-last-mountain-lake-cultural-centre&Itemid=1819

### Past events are optional

Dates for current and upcoming events are listed first and past event are listed at the end.

**We need only crawl upcoming events.** But it is OK to crawl past events if it is more work to remove them.

This VA Page has Exhibitions and Past Exhibitions:
https://www.osac.ca/index.php?option=com_content&view=article&id=157&artist=All+Conditioned+Things%3A+Jared+Boechler+and+Nic+Wilson&Itemid=1822
 
None of the Performing Arts pages have Past Performances yet as our season has not started, but once the dates are past those performances move to a Past Performances list below the current list.

**Comment by dev-aravind** [comment]
@saumier The data is crawled and up in artsdata right now. I did not see any blank nodes for events so that is unchanged and also there is a SHACL violation related to the location. Please review this and let me know.

**Comment by saumier** [comment]
@dev-aravind I have added more instructions on how to crawl the site after speaking with their developer today. His name is Skip.  There is a lot more data that we should crawl. This is low priority and can be done when you have a good opportunity in the coming weeks.

The SHACL violation is because there is no address in the location. But I spoke with Skip about this today and we were crawling the wrong pages. See above.

**Comment by saumier** [comment]
@dev-aravind Please move this to a new repo called `artsdata-planet-osac` and create 2 artifacts: `performing-arts` and `visual-media-arts`. I expect a lot of collaboration with OSAC so having a repo where we can share documentation and a pipeline that they will have permission to run will be helpful. We can add their developer Skip to this new repo and share github issues with him.

**Comment by dev-aravind** [comment]
@saumier. The data is now imported into [Artsdata](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?sparql=feeds_all&title=Data+Feeds). I also updated the code to remove the blank nodes at the Event level. However, the exhibition had events of type http://schema.org/VisualArtsEvent, which was not recognized by Nebula. Please take a look into this and let me know if you see any issues.

**Comment by saumier** [comment]
@dev-aravind 

1. The Event type schema:VisualArtsEvent is now recognized. Note: The link was clickable event with 0 but not it displays 96 events.


Still to do:
- [x] Please add the SPARQL add_derived_from.sparql in all cases where we scrape a list of webpages. This ensures there is a link back to the url of the Webpage that was scraped. https://github.com/culturecreates/artsdata-orion/blob/main/sparql/add_derived_from.sparql
- [x] There are only [9 performing arts events](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20performing-arts&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-osac/performing-arts) but when I look at the website I see many more. Can you confirm that you are following the instructions for performing arts events in the description of this issue?

**Comment by dev-aravind** [comment]
@saumier I added the SPARQL and fixed the issues with the missing events. Turns out some of the Events are throwing an error when we are trying to extract the RDF. For example, all the events in [this](https://www.osac.ca/index.php?option=com_content&view=article&id=156&Itemid=1821&artist=Burnt%2BThicket%2BTheatre%2Bpresents%2BEvery%2BBrilliant%2BThing) event series is not being crawled. 

```
Error loading RDF from https://www.osac.ca/performing-arts/event/121-PA8783/burnt-thicket-theatre-presents-every-brilliant-thing-tisdale-arts-council: Failed to parse input document: loading document failed: 859: unexpected token at '{
					"@context": "https:\/\/schema.org",   
					"@type": "Event", 
					"name": "Burnt Thicket Theatre presents Every Brilliant Thing",
					"startDate": "2025-03-21T01:30:00+00:00",
					"endDate": "2025-03-21T03:30:00+00:00",	
					"eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",	
					"eventStatus": "https://schema.org/EventScheduled",	
					"url": "https://osac.ca/performing-arts/event/121-PA8783/burnt-thicket-theatre-presents-every-brilliant-thing-tisdale-arts-council",	
					"identifier": "PA8783",	
					"additionalType": "http://kg.artsdata.ca/resource/PerformingArtsEvent",		
				        "image": "https:\/\/www.osac.ca\/images\/PA\/images\/EveryBrilliantThing.jpg",
"performer": {
    "@type": "Organization",
    "name": "Burnt Thicket Theatre presents Every Brilliant Thing",
    "sameAs": [
        "https://www.facebook.com/BurntThicket",
        "https://twitter.com/BurntThicket",
        "https://www.instagram.com/burntthicket/"
    ]
}
```

This is the error that is thrown. Previously the process would stop on an error. I've modified the code to run completely even if some of the URLs are not working.
