### ISSUE TITLE
Estimate WO-5 Crawl OSAC's JSON-LD

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-osac#4]
View detailed crawl instructions in https://github.com/culturecreates/artsdata-planet-osac/issues/1 and estimate work

Work Order doc for Gregory to fill in once he has estimate: https://docs.google.com/document/d/1krRWkKYVh8woshxsS66bk5tFSyNsetIygu91PCVXtGA/edit

**Comment by dev-aravind** [comment]
@saumier 

Estimate - 

Initializing the work and repository - 1h
Workflow to Crawl Performing Arts - 8h
Workflow to crawl Visual Media Arts - 6h

Total - 15h
